Use apple SDK 11 on x86_64-darwin
By default, apple-sdk 10.12 is used.

For graalVM, this caused some warnings during linking:

```
ld: warning: object file (/nix/store/fq9j83jfdz7ia200xs06mbag3yplcyf8-graalvm-ce-23.0.0/lib/static/darwin-amd64/libnio.a(DatagramChannelImpl.o)) was built for newer macOS version (11.0) than being linked (10.12)
```

and eventually failed:

```
Undefined symbols for architecture x86_64:
[info]   "____chkstk_darwin", referenced from:
[info]       _InflateFully in libzip.a(zip_util.o)
[info]       _checkCPUFeatures in liblibchelper.a(cpuid.o)
[info]       _readBytes in libjava.a(io_util.o)
[info]       _writeBytes in libjava.a(io_util.o)
[info]       _collapse in libjava.a(path_util.o)
[info] ld: symbol(s) not found for architecture x86_64
```

For the nix package on x86_64-darwin, this failed with:

```
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -target
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: x86_64-macos.11.0-none
In file included from /nix/store/95w005yswa7h4im5ya0inmqpp9lvavbf-zig-0.13.0/lib/zig/libcxx/src/new.cpp:10:
/nix/store/95w005yswa7h4im5ya0inmqpp9lvavbf-zig-0.13.0/lib/zig/libcxx/include/__memory/aligned_alloc.h:43:12: error: no member named 'aligned_alloc' in the global namespace
   43 |   return ::aligned_alloc(__alignment, __size > __rounded_size ? __size : __rounded_size);
      |          ~~^
1 error generated.
```